<?php
/**
 * @file
 * Code for the Stanford Video feature.
 */

include_once 'stanford_video.features.inc';

/**
 * Implements hook_theme().
 */
function stanford_video_theme($existing = 'jw_player') {
  return array(
    'jw_player' => array(
      'variables' => array(
        'file_object' => NULL,
        'sources' => '',
        'streamer' => '',
        'preset' => '',
        'image' => '',
        'options' => array(),
        'entity' => NULL,
        'entity_type' => '',
        'captions' => '',
      ),
      'template' => 'theme/stanford_jw_player',
    ),
  );
}

/**
 * Process variables for jw_player.tpl.php.
 *
 * @param $variables
 *   An array that must contain one (and only one) of the following:
 *   - $file_object The file object you would like JW Player to play.
 *   - $sources If you would like to play a URL directly instead of a file
 *     object the URL can be passed directly to the theme function. The file URL
 *     must be provided within an array. This is helpful for playing back the
 *     contents of link fields. Optionally the array can contain multiple URLS
 *     to allow for multiple video formats or adaptive bitrate switching. Here
 *     is a sample sources array that contains two formats of a video:
 *
 *     @code
 *     $variables['sources'] = array(
 *       array(
 *         'file_path' => 'http://example.com/video.ogg',
 *         'file_mime' => 'video/ogg',
 *       ),
 *       array(
 *         'file_path' => 'http://example.com/video.m4v',
 *         'file_mime' => 'video/mp4',
 *       ),
 *     );
 *     @endcode
 *
 *     To use adaptive bitrate switching two additional parameters - with and
 *     and bitrate are to be provided. *Note that adaptive bitrate is only
 *     supported in the flash version of the player. In preprocessing the player
 *     will automatically switch to flash playback mode when two sources are
 *     supplied with bitrates.
 *
 *   The following optional variables can also be set:
 *   - $preset (highly recommended!) The machine name of the JW Player preset
 *     you would like to use. Template preprocessing will take care of applying
 *     the preset's settings for you.
 *   - $image URL for the image ("poster" in HTML 5 video) to use as the video
 *     preview.
 *   - $options Additional options for the player. These options will override
 *     The module's defaults as well as the presets defaults.
 *
 * @see jw_player.tpl.php
 */
function stanford_video_preprocess_jw_player(&$variables) {
  if (isset($variables['file_object'])) {
    if (empty($variables['file_url'])) {
      $variables['file_url'] = file_create_url($variables['file_object']->uri);
    }
    //if a URL couldn't be created, set it to the remote URI
    // @todo this can probably be fixed with https://drupal.org/project/filter_protocols; see https://drupal.org/node/685592
    if (empty($variables['file_url'])) {
      $variables['file_url'] = $variables['file_object']->uri;
    }
  }
//  $variables['config']['file'] = $variables['file_object']->uri;
  $variables['config']['file'] = 'pickles.mp4';
  $variables['config']['streamer'] = 'rtmp://sv-stream.stanford.edu/su-webservices/';
  $variables['config']['caption'] = 'http://localhost:8888/videod7/sites/default/files/captions/pickles_0.srt';
//  dpm($variables);
}
